### PR TITLE
Move connection events to reducers

### PR DESCRIPTION
**Pull request by RReverser**
# Description of Changes

(WIP) This changes `__identity_connected__` and `__identity_disconnected__` to become plain reducers instead of Wasm exports.

# API and ABI

 - [x] This is a breaking change to the module ABI
 - [x] This is a breaking change to the module API
 - [ ] This is a breaking change to the ClientAPI
 - [ ] This is a breaking change to the SDK API

*If the API is breaking, please state below what will break*

### CODE REVIEW

**Comment by gefjon** [comment]
If you rename the bindings to be `__client_connected__` and `__client_disconnected__`, then I won't have to do it in #299 .

**Comment by RReverser** [comment]
> If you rename the bindings to be `__client_connected__` and `__client_disconnected__`

Hm what do you mean? I don't see those names in #299, and those are no longer bindings - they're just reducers.

**Comment by gefjon** [comment]
I haven't made that change yet in #299, but I need to. Whether they're reducers or special functions, with #299 the name `__identity_connected__` will no longer be accurate. (Arguably it was never accurate, since it was always possible to have multiple concurrent connections from the same identity, but now we're acknowledging that fact.)

**Comment by RReverser** [comment]
Ah ok... in that case let's just leave it for a separate PR since it's technically an improvement out of scope of either of those PRs. The smaller PRs, the easier to deal with said merge conflicts.

**Comment by gefjon** [comment]
Ugh, that same mysterious should-be-unreachable failure in the SDK tests. Sigh.

**Review by cloutiertyler — CHANGES_REQUESTED** [review]
Please fix the broken smoke tests.

**Review by cloutiertyler — APPROVED** [review]
LGTM

**Pull request merged**
