### PR TITLE
Rebase #1455 onto master

### PR DESCRIPTION
**Pull request by kazimuth**
Squash and rebase #1455. The rebase succeeded automatically, flawlessly, so I'm opening this to run the tests.

# Description of Changes

See #1455.

### CODE REVIEW

**Comment by kazimuth** [comment]
bots please

**Comment by bfops** [comment]
Adding the `do not merge` label since I assume we're still planning to merge #1455 as the "official" PR

**Comment by kazimuth** [comment]
FWIW, looks like the bots here ran with flying colors.

**Comment by kazimuth** [comment]
Did not mean to do that.

**Pull request closed without merging**
