### PR TITLE
Optimize DatabaseUpdate::from_writes (doesn't need db access at all)

### PR DESCRIPTION
**Pull request by coolreader18**
# Description of Changes

Turns out we don't need to do any lookups to find the table name here at all - it's all already there for us.

# Expected complexity level and risk

1

### CODE REVIEW

**Review by Shubham8287 — APPROVED** [review]
This is a good change! LGTM :heavy_check_mark:

**Comment by bfops** [comment]
# Bot test results
**Conclusion**: I think this mainly shows an improvement for `eval` - does that sound reasonable @coolreader18 ?

### Commits tested
before:
```
commit 9c4a321c2a616f5a94b5e0fcf69a0169cd31a848 (origin/bfops/perf-test-before)
Merge: a05aed4e 0ad01b77
Author: Zeke Foppa <196249+bfops@users.noreply.github.com>
Date:   Thu Mar 21 13:53:18 2024 -0700

    [bfops/perf-test-before]: Merge remote-tracking branch 'origin/bfops/enable-tracy' into bfops/perf-test-before

commit a05aed4e9a8b39e3be8c74e4a247a15d3d71c805
Author: Mazdak Farrokhzad <twingoow@gmail.com>
Date:   Thu Mar 14 19:16:04 2024 +0100

    Code motion: QueryCode => QueryExpr; CrudCode => CrudExpr (#975)
    
    * QueryCode.{table -> source}
    
    * nix QueryCode; identical to QueryExpr
    
    * nix CrudCode; use identical CrudExpr instead
```
after:
```
commit acec507621bb11af0a3068ba3ef076024f9abd16 (HEAD -> bfops/perf-test-after, origin/bfops/perf-test-after)
Merge: 4ea8c45b 0ad01b77
Author: Zeke Foppa <196249+bfops@users.noreply.github.com>
Date:   Thu Mar 21 13:53:22 2024 -0700

    [bfops/perf-test-after]: Merge remote-tracking branch 'origin/bfops/enable-tracy' into bfops/perf-test-after

commit 4ea8c45b1f0648c761cdbf5197f4367306604a5b (origin/noa/dbupdate_fromwrites_opt)
Author: Noa <coolreader18@gmail.com>
Date:   Mon Mar 11 16:24:38 2024 -0500

    Optimize DatabaseUpdate::from_writes (doesn't need db access at all)
```
### `eval`
(no `eval_incr`?)
image

### `eval_updates`
image

### `enemy_ai_agent_loop`
image

### `npc_ai_agent_loop`
Note: This showed a small performance degradation, but I suspect it was spurious; it has the fewest samples, and it shrank as more samples appeared.
image

**Comment by joshua-spacetime** [comment]
@bfops this change is outside of (before) eval_updates. It should be reflected in `call_reducer_with_tx`

**Comment by bfops** [comment]
> @bfops this change is outside of (before) eval_updates. It should be reflected in `call_reducer_with_tx`

Ah blergh, that’s probably a result of me merging in `bfops/enable-tracy`, which has a more recent base.

would it be better to re-run this faithfully to the version of master it’s based on?

**Comment by bfops** [comment]
Hmm, now this seems a tad slower? I tested one with the world load time & logins, and once without.
image
image

**Comment by bfops** [comment]
Maybe some improvements in `call_reducer` and `call_reducer_with_tx`? Mostly still looks like some improvements in the `eval*` tree.. maybe it's all within the realm of machine-induced test noise :sweat_smile: 

image
image

image
image
image

**Comment by coolreader18** [comment]
Closing when this is gonna be sorta superseded by the client api overhaul

**Pull request closed without merging**
