### PR TITLE
Logging API

### PR DESCRIPTION
**Pull request by SteveBoytsun**
# Description of Changes

Changed logging based on [this proposal](https://github.com/clockworklabs/SpacetimeDBPrivate/pull/981)

# API and ABI breaking changes

If this is an API or ABI breaking change, please apply the
corresponding GitHub label.

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

1

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

# Testing

*Describe any testing you've done, and any testing you'd like your reviewers to do,
so that you're confident that all the changes work as expected!*

- [x] You can test it by calling the following reducer
 ```cs
[Reducer]
public static void testt(ReducerContext ctx)
{
    Log.Debug("1");
    Log.Trace("2");
    Log.Info("3");
    Log.Warn("4");
    Log.Error("5");
    Log.Exception("6");
}
```
Note: STDB doesn't differentiate between error and exception, so the last two logs are both errors

### CODE REVIEW

**Comment by RReverser** [comment]
We have quite a few modules and templates using `Runtime.Log`, including in runtime tests. You're going to want to update all of those too (just search the entire codebase).

**Comment by SteveBoytsun** [comment]
> We have quite a few modules and templates using `Runtime.Log`, including in runtime tests. You're going to want to update all of those too (just search the entire codebase).

Good catch, fixed (not as many as I thought there would be)

**Comment by RReverser** [comment]
> Good catch, fixed (not as many as I thought there would be)

CI still complains about a missed template for `spacetime generate` used in smoketests. You probably used "find references" instead of textual search.

**Comment by SteveBoytsun** [comment]
> CI still complains about a missed template for `spacetime generate` used in smoketests. You probably used "find references" instead of textual search.

I did do textual search. It actually seems to be the opposite problem - smoketests are using old version of SDK for some reason. I'm not sure how to fix it, let's discuss in today's meeting
>  /tmp/tmp4jexmxj5/Lib.cs(19,9): error CS0103: The name 'Log' does not exist in the current context [/tmp/tmp4jexmxj5/StdbModule.csproj]

**Comment by RReverser** [comment]
Ahh ok, sorry. Yeah it checks out C# SDK here https://github.com/clockworklabs/SpacetimeDB/blob/3fcb5056b205f69c84e9e6888264fad28032a182/.github/workflows/ci.yml#L117-L119 - it points to master by default, but for your usecase it would need to be changed to point to your branch.

Cross-repo testing is annoying.

**Review by RReverser — APPROVED** [review]
Looks good, thanks. The CI issue is not something we can fix at the moment, but as long as you tested them locally, it should be fine.

**Comment by cloutiertyler** [comment]
I force merged this because of the API breaking changes at Steve's and Ingvar's request

**Comment by joshua-spacetime** [comment]
@RReverser is there a PR that fixes the failing smoketest?

**Pull request merged**
