### PR TITLE
Update tools/publish-crates.sh

### PR DESCRIPTION
**Pull request by bfops**
# Description of Changes

Did my best to update `tools/publish-crates.sh` with the crates that seemed to be missing.

I have no idea if I did this correctly, but did my best to maintain them in order of how they depend on each other.

# Expected complexity level and risk

1

# Testing

This branch contains the version that @kurtismullins tested during the last deploy

### CODE REVIEW

**Comment by bfops** [comment]
> @bfops Here were the changes I ultimately needed to successfully publish to crates.io in the v0.10.0-beta tag. I haven't checked to see if they match yours in this PR; if so, feel free to let me know and I'll approve it so you can get it merged.
> 
> At the moment, I am shoulder-deep in this release.
> 
> ```diff
> -declare -a CRATES=("metrics" "primitives" "bindings-macro" "bindings-sys" "sats" "lib" "bindings" "vm" "client-api-messages" "core" "client-api" "standalone" "cli" "sdk")
> +declare -a CRATES=("metrics" "primitives" "bindings-macro" "bindings-sys" "data-structures" "sats" "lib" "bindings" "table" "vm" "client-api-messages" "commitlog" "durability" "fs-utils" "snapshot" "core" "client-api" "standalone" "cli" "sdk")
> ```

@kurtismullins It's all the same crates as is in this PR. So to check - you started with the version of the script in the release branch (which is the same as the one in this PR), and it didn't work, so you had to reorder the crates to the version you have now?

**Comment by bfops** [comment]
> ```diff
> declare -a CRATES=("metrics" "primitives" "bindings-macro" "bindings-sys" "data-structures" "sats" "lib" "bindings" "table" "vm" "client-api-messages" "commitlog" "durability" "fs-utils" "snapshot" "core" "client-api" "standalone" "cli" "sdk")
> ```

@kurtismullins Updated to this exact ordering

**Review by cloutiertyler — APPROVED** [review]

**Comment by kurtismullins** [comment]
> > @bfops Here were the changes I ultimately needed to successfully publish to crates.io in the v0.10.0-beta tag. I haven't checked to see if they match yours in this PR; if so, feel free to let me know and I'll approve it so you can get it merged.
> > At the moment, I am shoulder-deep in this release.
> > ```diff
> > -declare -a CRATES=("metrics" "primitives" "bindings-macro" "bindings-sys" "sats" "lib" "bindings" "vm" "client-api-messages" "core" "client-api" "standalone" "cli" "sdk")
> > +declare -a CRATES=("metrics" "primitives" "bindings-macro" "bindings-sys" "data-structures" "sats" "lib" "bindings" "table" "vm" "client-api-messages" "commitlog" "durability" "fs-utils" "snapshot" "core" "client-api" "standalone" "cli" "sdk")
> > ```
> 
> @kurtismullins It's all the same crates as is in this PR. So to check - you started with the version of the script in the release branch (which is the same as the one in this PR), and it didn't work, so you had to reorder the crates to the version you have now?

I started with the script that was in the tag and had to add missing crates.

**Review by kurtismullins — APPROVED** [review]
LGTM

**Pull request merged**
