### PR TITLE
Fix benchmarks please 100%

### PR DESCRIPTION
**Pull request by coolreader18**
# Description of Changes

# API and ABI

 - [ ] This is a breaking change to the module ABI
 - [ ] This is a breaking change to the module API
 - [ ] This is a breaking change to the ClientAPI
 - [ ] This is a breaking change to the SDK API

*If the API is breaking, please state below what will break*

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

### CODE REVIEW

**Comment by coolreader18** [comment]
I'm actually not necessarily 100% on this but I'm kinda confused. the error is "Message: Resource not accessible by personal access token, Locations: [{Line:1 Column:49}]", which looking at the github cli source code seems to indicate that it's a graphql error. but this isn't using graphql? so idk what the deal is

**Comment by coolreader18** [comment]
ohhh ok now I think I get it

**Comment by coolreader18** [comment]
though that would still mean that the check is failing :/

**Comment by coolreader18** [comment]
ok maybe I'll just try something real quick

**Comment by coolreader18** [comment]
for faster iteration

**Comment by coolreader18** [comment]
Ok, NOW I'm confident this'll work.

**Review by kurtismullins — APPROVED** [review]
Nice! LGTM

**Pull request merged**
