### PR TITLE
BTreeIndex: use `ReadColumn` instead of `ProductValue` fields

### PR DESCRIPTION
**Pull request by gefjon**
# Description of Changes

Prior to this commit, `BTreeIndex::insert` and `BTreeIndex::delete` took a `&ProductValue`, the row to be inserted or deleted, as an argument, and extracted the indexed column value(s) from it.

With this commit, we instead take a `RowRef` referring to the row to be inserted or deleted, and access the indexed column value(s) using `ReadColumn`. For specialized indexes, we extract them directly as native types, rather than as `AlgebraicValue`.

Making this change involved a nasty split borrow problem, as we now need to have a `RowRef` to the inserted/deleted row coexisting with a mutable borrow of the index to be modified. This required introducing a `TableInner` struct,
which is the referent of `RowRef`.

# API and ABI breaking changes

No external interfaces broken.

# Expected complexity level and risk

2 - minimal `unsafe`, semantics of `Table`, `RowRef` and `BTreeIndex` preserved.

### CODE REVIEW

**Comment by gefjon** [comment]
Callgrind please

**Review by kazimuth — APPROVED** [review]
👍 

Unsafe audit:
- [x] RowRef::new

**Comment by gefjon** [comment]
callgrind please

**Comment by gefjon** [comment]
benchmarks please

**Comment by gefjon** [comment]
Hard to tell what's noise and what's real changes from the wall-time benchmarks, but it seems like this is neither a major performance gain or loss. That's good enough for me to want to merge, as this PR will make it easier down the line to remove the `ProductValue` return from `Table::delete`, and serves as a good template for how we can use `ReadRow` in other parts of the codebase.

**Comment by gefjon** [comment]
Running benchmarks locally (hopefully less noisy?) to confirm, then will merge.

**Comment by gefjon** [comment]
Pretty much the same story locally. Some improvements, some regressions, some noise, nothing groundbreaking.

**Comment by cloutiertyler** [comment]
It's surprising that multi row unique raw mem insertions have no impact given what I measured.

**Pull request merged**
